remote:
    address: 47.110.79.29


spring:
    rabbitmq:
        addresses: 47.110.79.29
        username: admin
        password: wxc123...
        virtual-host: /
    data:
        redis:
            host: 47.110.79.29
            port: 6379
            password: wxc123...
    jackson:
        # 格式为yyyy-MM-dd HH:mm:ss
        date-format: yyyy-MM-dd HH:mm:ss
        # 定时区，解决8小时的时间差问题
        time-zone: GMT+8
    mvc:
        path-match:
            # 配置策略
            matching-strategy: ant-path-matcher
    datasource:
        # 连接池类型
        type: com.alibaba.druid.pool.DruidDataSource
        # Druid的其他属性配置 springboot3整合情况下,数据库连接信息必须在Druid属性下!
        druid:
            url: jdbc:mysql://47.110.79.29:3306/db_oj
            username: root
            password: wxc123...
            driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
    configuration:
        # 配置MyBatis日志
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
            logic-delete-value: 1 # 逻辑已删除值(默认为 1)
            logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
            # 配置MyBatis-Plus操作表的默认前缀
            # table-prefix: t_
            # 配置MyBatis-Plus的主键策略
#            id-type: assign_id #雪花算法
    mapper-locations: classpath:mapper/*.xml


# 自定义token的配置属性
jwt:
    token:
        tokenExpiration: 86400000 # 有效时间ms
        tokenSignKey: onlinejudge # 签名密钥


server:
    tomcat:
        max-http-form-post-size: 20MB
    reactive:
        session:
            timeout: 8000
    port: 8080
    address: 0.0.0.0
    servlet:
        context-path: /api






api-key:
    imgbb: fb45ec0a10c46133498a09b082867203



# oj配置
oj:
    data:
        path: E:\oj-data # 动态路径
    judge:
        cpu-limit: 1000000000 # 1s
        compile-cpu-limit: 3000000000 # 3s
        memory-limit: 536870912 # 512MB
        proc-limit: 50
    language:
        cpp:
            source-file-name: main.cpp
            exe-file-name: main
            cmp-args: ["g++", "main.cpp", "-o", "main"]
            exe-args: ["./main"]
            envs: []
        java:
            source-file-name: Main.java
            exe-file-name: Main.class
            cmp-args: ["javac", "Main.java"]
            exe-args: ["java", "Main"]
            envs: []
        python:
            source-file-name: main.py
            exe-file-name: main.py
            cmp-args: [] # 无编译步骤
            exe-args: ["python", "main.py"]
            envs: []